### ISSUE TITLE
Wrong range when motion is 'block

### ISSUE THREAD

**Issue by Dickby** [edkolev/evil-goggles#1]
I know that this is a more rare case, but in visual-block range the wrong area is highlighted.
example
`d C-v 5 j`
the range is highlighted as it would be just visual-state not the block.

**Comment by edkolev** [comment]
Nice catch.

I'll disable the highlighting in this case for now, and maybe get back to it later.

**Comment by edkolev** [comment]
https://github.com/edkolev/evil-goggles/commit/cb295a7f6882f7b885886aca8bb88ce119973f40

**Comment by edkolev** [comment]
This is now supported.

However, I occasionally get this error `Wrong type argument: wholenump, 6.0` when using a vertical block range (e.g. `C-v 5 j`). I get this error with and without evil-goggles-mode. I'll submit a PR to evil if I manage to fix this.
