### ISSUE TITLE
I get this error when trying to install this with use-package.

### ISSUE THREAD

**Issue by justinjk007** [edkolev/evil-goggles#11]
`error: Package `emacs-25' is unavailable`

I am on Linux by the way, when I installed this yesterday on my windows machine it worked fine, so I am thinking a possible update might have broken it. 

Thanks

**Comment by edkolev** [comment]
This package requires emacs 25. Could this strange message mean your emacs is older?

**Comment by justinjk007** [comment]
```GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.```

Also I should ask why do you need Emacs 25 anyways ?

**Comment by edkolev** [comment]
For `funcall-interactively` if I remember correctly.

Do you have 25 or not?

**Comment by justinjk007** [comment]
I guess I'm gonna have built it again. Thanks

**Comment by edkolev** [comment]
You should be able to get the version with `M-x emacs-version` even if you built it from source. I build it from source when I'm on Ubuntu as well

**Comment by justinjk007** [comment]
That's strange, its started working

**Comment by edkolev** [comment]
Hm.. maybe Melpa had some downtime?
