### ISSUE TITLE
Visual hints slow down bulk actions using multiple cursors (evil-mc)

### ISSUE THREAD

**Issue by gilbertw1** [edkolev/evil-goggles#12]
Hi, I think your package is awesome! However it appears to have a minor quirk when working with multiple cursors using evil-mc. When I perform a bulk action like changing or deleting several words at once with multiple cursors, each action is performed one at a time waiting on the animation of the previous one to complete. 

You can see an [example of the behavior here](http://drop.bryan.sh/Sh0sZuszPQ.mp4).

I would imagine a good solution would be to either disable visual hints when multiple cursors are active or potentially perform all of the hints simultaneously. One other option might be to expose some sort of predicate that can be overridden that would let an end user determine if hints should be run or not.

Thanks!

**Comment by gilbertw1** [comment]
Also for reference, here is my hack workaround:

```elisp
  (defun my-evil-goggles--show-p (orig-fun &rest args)
    (when (not (and (fboundp 'evil-mc-has-cursors-p) (evil-mc-has-cursors-p)))
      (apply orig-fun args)))

  (advice-add 'evil-goggles--show-p :around #'my-evil-goggles--show-p)

```

**Comment by edkolev** [comment]
Thanks, I'm glad you like the package! I'll look into this and probably use
some bits of the code you provided to disable the hint when multiple
cursors are active

**Comment by edkolev** [comment]
Thanks again, I just pushed this commit, based on the snippet you provied https://github.com/edkolev/evil-goggles/commit/879114abeaad8515937cb2a762d0438b6b7bb026

Please let me know in case this doesn't work for you.

**Comment by gilbertw1** [comment]
Works perfectly, thank you!
