### ISSUE TITLE
Support Emacs 24 ?

### ISSUE THREAD

**Issue by vindarel** [edkolev/evil-goggles#14]
Hello,

I'm eager to try this neat package, however it requires Emacs 25. On reddit, skeeto may have a fix:

> The only thing that ties it to Emacs 25 is funcall-interactively. This can be simulated well enough with cl-letf. However, I tried changing all of the funcall-interactively to plain old funcall and it seems to work just fine in Emacs 24.

https://www.reddit.com/r/emacs/comments/6x5zzc/evil_goggles_display_visual_hint_on_evil_edit/dmfbl6f/

and I can confirm.

regards

ps: and so cool tip, I didn't know `=ip` :)

**Comment by edkolev** [comment]
Hi, thanks for the info!

From what I've tested, `funcall` works 99% of the times.

Unfortunately, some functions in evil behave differently based on what `called-interactively` returns. If I remember correctly, pasting in insert state had a subtle difference in its behaviour.

However, I just did some tests with pasting in insert state without `funcall-interactively` and I can't see any issues.

I'll revert the code locally to use a plain `funcall` and use evil-goggles for some time, 1 week maybe. Then, if I don't see any issues, I'll re-add support for emacs 24 by removing the `funcall-interactively`.

Thanks again!

**Comment by vindarel** [comment]
good plan, thanks !

**Comment by edkolev** [comment]
I ran into the following inconsistency when using `funcall` instead of `funcall-interactively`:

- with this text
```
;; This buffer is for notes you don't want to save.
;; [I]f you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.
```
- press `2dd`
- result with `funcall` is:
```
;; This buffer is for notes you don't want to save[.]
```
- result with `funcall-interactive` is:
```
[;]; This buffer is for notes you don't want to save.
```

The difference is in the cursor placement. The correct behaviour is the second one, `funcall-interactive`.

**Comment by edkolev** [comment]
@vindarel with this commit https://github.com/edkolev/evil-goggles/commit/221a5ed8ea0455e4274ef9ba14fe852cc512112d I believe evil-goggles should work on Emacs 24.4. Please let me know if it does for you.

**Comment by vindarel** [comment]
I've been using my own tweak with success, this one works well too. Thanks !

**Comment by edkolev** [comment]
Great, thanks!
