### ISSUE TITLE
(evil-goggles-enable-delete nil) only works in conjunction with yank

### ISSUE THREAD

**Issue by InspectorMustache** [edkolev/evil-goggles#18]
First of all, thank you very much for this great package.

I'm having trouble setting delete and yank hints independently.
When I do this:
```
(setq evil-goggles-enable-delete nil)
(evil-goggles-mode)
```
I still get the hint animation when I delete something.

When I do this:
```
(setq evil-goggles-enable-yank nil)
(setq evil-goggles-enable-delete nil)
(evil-goggles-mode)
```
it works fine but now I've lost the hint for yanking. Is this a bug? And if no, how can I disable hints on deletion only?

**Comment by edkolev** [comment]
Hey, thanks for reporting this, it's definitely a bug.

Would you mind sharing why you want to disable it? I'd like to better understand how people use the package. I've seem in doom's configuration examples disabling something similar (not sure if it was delete hint exactly).

Anyway, here's a workaround until there's a fix:
```
  (setq evil-goggles-blocking-duration 0.001)
```

**Comment by edkolev** [comment]
Would you mind testing the `hint-only-when-command-is-interactive` branch with this configuration:
```elisp
  (setq evil-goggles-enable-substitute nil)
  (setq evil-goggles-enable-change nil)
  (setq evil-goggles-enable-delete nil)
  (evil-goggles-mode)
```

Thanks!

**Comment by edkolev** [comment]
Hi, no worries.

I just merged in master, please let me know in case it's not working for you.
