### ISSUE TITLE
evil-change with surround is broken by evil-goggles

### ISSUE THREAD

**Issue by ppwwyyxx** [edkolev/evil-goggles#19]
Behavior:
Buffer content is `(abc d|ef)`. (cursor at "d")
After pressing `cs)]`, the buffer becomes `ef]`.

Expected behavior:
buffer becomes `[abc def]`

Setting `(setq evil-goggles-enable-change nil)` can fix this issue.

**Comment by edkolev** [comment]
Hey, this is now fixed in master.

To fix this issue, and not break evil-goggles on emacs 24.4, I had to refactor the code base.

As a result of the refactor the code is much simpler now.

Please let me know if you run into any issues.
