### ISSUE TITLE
Visual feedback not shown in org-mode

### ISSUE THREAD

**Issue by rgemulla** [edkolev/evil-goggles#21]
Some visual feedback is not shown in org-mode in my setup. For example, ```D``` or ```cw``` work for me in both text-mode and org-mode, whereas ```dw``` or ```dd``` show visual feedback in text-mode but do not show any feedback in org-mode. 

Not sure if this is related to my setup or a general problem. I am on Emacs 26.1 and use the development version of Spacemacs.

**Comment by edkolev** [comment]
Does spacemacs use `evil-org`? If yes, then that would explain it - evil-org overwrites the `d` key https://github.com/Somelauw/evil-org-mode/blob/b6d652a9163d3430a9e0933a554bdbee5244bbf6/evil-org.el#L651

Could you confirm your `d` key in normal state does run `evil-org-delete`? You can use `M-x describe-key` to check.

**Comment by rgemulla** [comment]
Yes, Spacemacs uses evil-org and ```d``` is indeed bound to ```evil-org-delete```.

**Comment by edkolev** [comment]
Should be working now, please let me know if you run into any issues.

In addition to `d`, it turned out evil-org re-maps `>` and `<` -- those two now show hint as well.

**Comment by rgemulla** [comment]
Seems to work flawlessly, thanks a lot!

**Comment by edkolev** [comment]
You're welcome
