### ISSUE TITLE
Causes `evil-paste-pop` to stop working

### ISSUE THREAD

**Issue by countvajhula** [edkolev/evil-goggles#34]
Hello!
It seems that `evil-paste-pop` does not work with evil-goggles activated.

# Reproducing it

1. In Normal state, yank any text using e.g. `yy`.
2. Yank a different piece of text - say another line (this step isn't actually necessary to reproducing the bug but illustrates the desired goal).
3. Paste somewhere else using `p`.
4. Immediately afterwards, hit `C-p` to cycle to the previous yanked item.

This results in the error:

```
Previous command was not an evil-paste: next-line
```

# Workaround

Disable evil-goggles for paste via the custom variable:

```
(use-package evil-goggles
  :custom
  (evil-goggles-enable-paste nil))
```

**Comment by edkolev** [comment]
Hi, which version of evil are you using? I regularly use C-p to cycle and haven't experienced this issue. I suspect something else might be the root cause.

**Comment by countvajhula** [comment]
I'm using the latest version of Evil from Git and the latest version of evil-goggles as well.

Looks like it's some interference with [this line](https://github.com/countvajhula/.emacs.d/blob/bbc1eed4554eff4d8ae0a9d998fbb42f504f13fd/my-init/task-environment.el#L77) in my config which implements [Vim's centering behavior](https://github.com/countvajhula/.emacs.d/blob/bbc1eed4554eff4d8ae0a9d998fbb42f504f13fd/my-init/utils.el#L59-L83) on jumps. For context, in Evil, jumping to any position outside the visible screen area will always recenter the screen. I find this disorienting since it doesn't give us any clues about proximity to the original location. In Vim, it will recenter only if the destination is more than one full screen away from the initial line, otherwise, it simply moves the screen until both source and destination are visible.

Looking at [the paste advice](https://github.com/edkolev/evil-goggles/blob/8f20a16e74016f37ad76dc4f2230d9b00c6df3c2/evil-goggles.el#L535-L552) in evil-goggles, it does use `evil-goto-mark`, so, quite possibly, by triggering the recentering advice it ends up obscuring the paste that was the "last command."

Some options could be:

- avoid using `evil-goto-mark` and instead query the point locations directly, e.g. by using `evil-get-marker`
- I could stop using my recentering advice, or find some way to avoid updating `last_command`
- I could use the above workaround of disabling paste with goggles
- any other ideas?

My inclination would be towards the first of these, since `interactive` functions like `evil-goto-mark` are likely to be advised in user config or have other side effects from third party libraries, so using non-interactive functions in library code would be a way to avoid this kind of interference.

**Comment by edkolev** [comment]
Thanks for the suggestion - `evil-goto-mark` makes sense.

Could you check if this version of the advice function fixes the issue for you:
```
(defun evil-goggles--paste-advice (_ &optional register yank-handler)
  "Advice for `evil-paste-before' and `evil-paste-after'.

REGISTER and YANK-HANDLER are the argumenets to the original functions."
  (when (and (or
              ;; paste called interactively (via `p', `P')
              (called-interactively-p 'interactive)
              ;; paste called via evil-paste-pop/evil-paste-pop-next (via `C-n', `C-p')
              (memq real-this-command '(evil-paste-pop evil-paste-pop-next)))
             (evil-normal-state-p))
    (let* ((beg (save-excursion (goto-char (evil-get-marker ?\[)) (if (eolp) (1+ (point)) (point))))
           (end (save-excursion (goto-char (evil-get-marker ?\])) (if (eolp) (1+ (point)) (point))))
           (is-vertical-block-pasted (evil-goggles--paste-vert-block-p register yank-handler)))
      (if is-vertical-block-pasted
          ;; XXX the async hint can't show vertical block hints - use a blocking hint if a vert block is pasted
          ;; XXX without the `(1+ end)', the vertical block hint is off by one
          (evil-goggles--show-blocking-hint beg (1+ end) is-vertical-block-pasted)
        (evil-goggles--show-async-hint beg end)))))
```

The change is pretty minimal:
```diff
modified   evil-goggles.el
@@ -542,8 +542,8 @@ REGISTER and YANK-HANDLER are the argumenets to the original functions."
               ;; paste called via evil-paste-pop/evil-paste-pop-next (via `C-n', `C-p')
               (memq real-this-command '(evil-paste-pop evil-paste-pop-next)))
              (evil-normal-state-p))
-    (let* ((beg (save-excursion (evil-goto-mark ?\[) (if (eolp) (1+ (point)) (point))))
-           (end (save-excursion (evil-goto-mark ?\]) (if (eolp) (1+ (point)) (point))))
+    (let* ((beg (save-excursion (goto-char (evil-get-marker ?\[)) (if (eolp) (1+ (point)) (point))))
+           (end (save-excursion (goto-char (evil-get-marker ?\])) (if (eolp) (1+ (point)) (point))))
            (is-vertical-block-pasted (evil-goggles--paste-vert-block-p register yank-handler)))
       (if is-vertical-block-pasted
           ;; XXX the async hint can't show vertical block hints - use a blocking hint if a vert block is pasted
```

**Comment by countvajhula** [comment]
@edkolev Works like a charm 🙂

**Comment by edkolev** [comment]
Great, the fix is in master!
