### ISSUE TITLE
support for evil-shift-left and evil-shift-right would be nice

### ISSUE THREAD

**Issue by wbolster** [edkolev/evil-goggles#5]
see title.

**Comment by wbolster** [comment]
i can come up with a pr for this, just let me know.

**Comment by edkolev** [comment]
This is a good addition! Closing since there's an open PR for this

**Comment by wbolster** [comment]
this issue should _not_ be closed (please reopen) since #9 has not been merged.  when you merge it github will automagically close this pr.
